# Generated by Django 4.2.2 on 2023-07-05 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('pic', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('chamber', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField(null=True)),
                ('program_name', models.CharField(max_length=100, null=True)),
                ('total_commands', models.PositiveSmallIntegerField(null=True)),
                ('species', models.CharField(default='none', max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('details', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('server_time', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('details', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='LotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('command_name', models.CharField(max_length=100)),
                ('wbt1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wbt2', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dbt1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dbt2', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('mc1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mc2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mc3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mc4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mc5', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('mc6', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('mc7', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('mc8', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('amc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wood_temp1', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('wood_temp2', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('flaps', models.PositiveSmallIntegerField(null=True)),
                ('heat', models.PositiveSmallIntegerField(null=True)),
                ('spray', models.PositiveSmallIntegerField(null=True)),
                ('fan_cw', models.PositiveSmallIntegerField(null=True)),
                ('fan_ccw', models.PositiveSmallIntegerField(null=True)),
                ('reserved', models.FloatField(null=True)),
                ('details', models.CharField(max_length=100, null=True)),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.lot')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
