# Generated by Django 4.2.2 on 2023-07-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotdata',
            name='rh',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
