# Generated by Django 4.2.3 on 2023-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_chamber", models.CharField(max_length=10, null=True)),
                ("time", models.DateTimeField(null=True)),
                ("type", models.CharField(max_length=100, null=True)),
                ("details", models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
