# Generated by Django 4.2.3 on 2023-07-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_statusreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='chamber',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
