# Generated by Django 4.2.3 on 2023-08-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_statusreport_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
        migrations.AlterField(
            model_name='lotdata',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lot'),
        ),
    ]
