# Generated by Django 4.2.3 on 2023-09-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_lotdata_amc_alter_lotdata_dbt1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusreport",
            name="lot_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.lot"
            ),
        ),
    ]
