# Generated by Django 4.2.3 on 2023-09-10 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_statusreport_lot_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lotdata",
            old_name="lot_id",
            new_name="lot",
        ),
        migrations.RenameField(
            model_name="statusreport",
            old_name="lot_id",
            new_name="lot",
        ),
    ]
